apiVersion: v1
kind: Namespace
metadata:
  name: actions-cluster-paul
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-paul
  namespace: actions-cluster-paul
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-paul
  namespace: actions-cluster-paul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql-paul
    spec:
      containers:
      - name: mysql-container-paul
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootpassword
          - name: MYSQL_DATABASE
            value: users_db
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-paul
  namespace: actions-cluster-paul
spec:
  selector:
    app: mysql-paul
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-paul
  namespace: actions-cluster-paul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-paul
  template:
    metadata:
      labels:
        app: backend-paul
    spec:
      containers:
      - name: backend-container-paul
        image: paulgiraldo/backend-k8:latest
        env:
          - name: DB_HOST
            value: mysql-service-paul
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: rootpassword
          - name: DB_NAME
            value: users_db
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-paul
  namespace: actions-cluster-paul
spec:
  type: LoadBalancer
  selector:
    app: backend-paul
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-paul
  namespace: actions-cluster-paul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-paul
  template:
    metadata:
      labels:
        app: frontend-paul
    spec:
      containers:
      - name: frontend-container-paul
        image: paulgiraldo/frontend-k8:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-paul
  namespace: actions-cluster-paul
spec:
  type: LoadBalancer
  selector:
    app: frontend-paul
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80