name: Workflow to deploy on k8's

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen del backend
        run: |
          cd backend
          docker build -t paulgiraldo/backend-k8:latest .

      - name: Autenticando en dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Publicando imagen al dockerhub...
        run: |
          docker push paulgiraldo/backend-k8:latest
  
  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen del frontend
        run: |
          cd frontend/angular-frontend
          docker build -t paulgiraldo/frontend-k8:latest .

      - name: Autenticando en dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Publicando imagen al dockerhub..
        run: |
          docker push paulgiraldo/frontend-k8:latest
  
  deploy-k8:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar kubectl....
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.CLUSTER_KUBE_CONFIG_K8 }}
        with:
          args: apply -f k8/